
#define	CMD_AXIS_SET_ORIGIN	0
#define CMD_AXIS_RAMP_UP	1
#define CMD_AXIS_DWELL		2
#define CMD_AXIS_RAMP_DOWN	3
#define CMD_AXES_EXECUTE	4
#define	CMD_AXIS_SET_ACCEL	5
#define	CMD_AXIS_SET_PULSE_LENGTH 6
#define	CMD_AXIS_CONFIG_AXIS	7

#define CMD_SET_IDLE_TIMEOUT	11
#define CMD_SET_ENABLE		12

#define CMD_HALT_PRU		15
